// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ShipType,
  ShipProperties,
  ShipBehavior,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  worldId: __t.u64().name("world_id"),
  owner: __t.option(__t.identity()),
  get shipType() {
    return ShipType.name("ship_type");
  },
  get properties() {
    return ShipProperties;
  },
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  buttons: __t.option(__t.u32()),
  serverTick: __t.u64().name("server_tick"),
  lastProcessedInputTick: __t.option(__t.u64()).name("last_processed_input_tick"),
  get behavior() {
    return __t.option(ShipBehavior);
  },
});
