// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const InputFrame = __t.object("InputFrame", {
  inputTick: __t.u64(),
  moveX: __t.f32(),
  moveY: __t.f32(),
  buttons: __t.u32(),
});
export type InputFrame = __Infer<typeof InputFrame>;

export const PlayerInputBuffer = __t.object("PlayerInputBuffer", {
  identity: __t.identity(),
  connectionId: __t.connectionId(),
  get inputs() {
    return __t.array(InputFrame);
  },
});
export type PlayerInputBuffer = __Infer<typeof PlayerInputBuffer>;

export const Ship = __t.object("Ship", {
  id: __t.u64(),
  owner: __t.option(__t.identity()),
  get shipType() {
    return ShipType;
  },
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  buttons: __t.option(__t.u32()),
  serverTick: __t.u64(),
  lastProcessedInputTick: __t.option(__t.u64()),
});
export type Ship = __Infer<typeof Ship>;

// The tagged union or sum type for the algebraic type `ShipType`.
export const ShipType = __t.enum("ShipType", {
  Raven: __t.unit(),
  Gat: __t.unit(),
});
export type ShipType = __Infer<typeof ShipType>;

export const SimulationTimer = __t.object("SimulationTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  serverTick: __t.u64(),
});
export type SimulationTimer = __Infer<typeof SimulationTimer>;

