// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const InputFrame = __t.object("InputFrame", {
  inputTick: __t.u64(),
  moveX: __t.f32(),
  moveY: __t.f32(),
  buttons: __t.u32(),
});
export type InputFrame = __Infer<typeof InputFrame>;

export const PlayerInputBuffer = __t.object("PlayerInputBuffer", {
  identity: __t.identity(),
  worldId: __t.u64(),
  connectionId: __t.connectionId(),
  get inputs() {
    return __t.array(InputFrame);
  },
});
export type PlayerInputBuffer = __Infer<typeof PlayerInputBuffer>;

export const Projectile = __t.object("Projectile", {
  id: __t.u64(),
  worldId: __t.u64(),
  get projectileType() {
    return ProjectileType;
  },
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  owner: __t.identity(),
  ship: __t.u64(),
  damage: __t.u32(),
  created: __t.timestamp(),
});
export type Projectile = __Infer<typeof Projectile>;

// The tagged union or sum type for the algebraic type `ProjectileType`.
export const ProjectileType = __t.enum("ProjectileType", {
  Bullet: __t.unit(),
});
export type ProjectileType = __Infer<typeof ProjectileType>;

export const Ship = __t.object("Ship", {
  id: __t.u64(),
  worldId: __t.u64(),
  owner: __t.option(__t.identity()),
  get shipType() {
    return ShipType;
  },
  get properties() {
    return ShipProperties;
  },
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  buttons: __t.option(__t.u32()),
  serverTick: __t.u64(),
  lastProcessedInputTick: __t.option(__t.u64()),
  get behavior() {
    return __t.option(ShipBehavior);
  },
});
export type Ship = __Infer<typeof Ship>;

// The tagged union or sum type for the algebraic type `ShipBehavior`.
export const ShipBehavior = __t.enum("ShipBehavior", {
  Traffic: __t.unit(),
});
export type ShipBehavior = __Infer<typeof ShipBehavior>;

export const ShipProperties = __t.object("ShipProperties", {
  projectileSpeed: __t.f32(),
  range: __t.f32(),
  damage: __t.u32(),
  thrust: __t.f32(),
  maxSpeed: __t.f32(),
  linearDamping: __t.f32(),
  accuracy: __t.f32(),
});
export type ShipProperties = __Infer<typeof ShipProperties>;

// The tagged union or sum type for the algebraic type `ShipType`.
export const ShipType = __t.enum("ShipType", {
  Raven: __t.unit(),
  Gat: __t.unit(),
});
export type ShipType = __Infer<typeof ShipType>;

export const SimulationTimer = __t.object("SimulationTimer", {
  scheduledId: __t.u64(),
  worldId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  serverTick: __t.u64(),
});
export type SimulationTimer = __Infer<typeof SimulationTimer>;

export const World = __t.object("World", {
  id: __t.u64(),
  radius: __t.f32(),
});
export type World = __Infer<typeof World>;

