// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import FireReducer from "../fire_reducer";
import SubmitPlayerInputReducer from "../submit_player_input_reducer";

export type FireParams = __Infer<typeof FireReducer>;
export type SubmitPlayerInputParams = __Infer<typeof SubmitPlayerInputReducer>;

